apiVersion: v1
kind: Service
metadata:
  name: www
  labels:
    app: www
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: www
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www
        image: treehub/www:$VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
